apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: app-flaskapp
      project: zenda
  replicas: 3
  template:
    metadata:
      labels:
        app: app-flaskapp
        project: zenda
    spec:
      containers:
      - name: webapp
        image: nidhinb143/webapp:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
        