apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
spec:
  selector:
    matchLabels:
      app: app-flaskapp
      project: zenda
  replicas: 3
  type: RollingUpdate 
    rollingUpdate:
      maxSurge: 50%  # Maximum number or percentage of pods that can be added
      maxUnavailable: 50%  # Maximum number or percentage of pods that can be unavailable
  template:
    metadata:
      labels:
        app: app-flaskapp
        project: zenda
    spec:
      containers:
      - name: webapp
        image: nidhinb143/webapp:latest
        ports:
        - containerPort: 3000
        imagePullPolicy: Always
