apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: app-flaskapp
    project: zenda
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000